package gymbookings7095;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import static java.lang.Integer.parseInt;
// import java.awt.List; // unlikely to be needed
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*; // List,ArrayList,Date
import javax.swing.DefaultComboBoxModel;
import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aaronmontgomery
 */
public class BookingForm extends javax.swing.JFrame {

    String item1;
    String item2;
    String username;
    Date chosenDate;
    Date chosenD;

    /**
     * Creates new form BookingForm
     */
    public BookingForm() {
        initComponents();
        // Pre-populate the combobox of members
        membersFill();
        BookingDate.setMinSelectableDate(new Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        cbxTime = new javax.swing.JComboBox<>();
        lblMemberIDBooking = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnUploadBooking = new javax.swing.JButton();
        btnContinueBooking = new javax.swing.JButton();
        staffName = new javax.swing.JLabel();
        cbxBookingMember = new javax.swing.JComboBox<>();
        BookingDate = new com.toedter.calendar.JDateChooser();
        togColour = new javax.swing.JToggleButton();
        lnlTitleBook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        lblDate.setText("DATE ");

        lblTime.setText("TIME");

        cbxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00" }));
        cbxTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTimeActionPerformed(evt);
            }
        });

        lblMemberIDBooking.setText("MemberID");

        jLabel1.setText("Staff Username");

        btnUploadBooking.setText("Upload Booking");
        btnUploadBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadBookingActionPerformed(evt);
            }
        });

        btnContinueBooking.setText("Continue");
        btnContinueBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueBookingActionPerformed(evt);
            }
        });

        staffName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cbxBookingMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBookingMemberActionPerformed(evt);
            }
        });

        BookingDate.setDateFormatString("yyyy-MM-dd");

        togColour.setText("Change colour");
        togColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togColourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMemberIDBooking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTime)
                            .addComponent(lblDate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnContinueBooking))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbxBookingMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUploadBooking)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(togColour))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate)
                    .addComponent(BookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(togColour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(cbxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberIDBooking)
                    .addComponent(cbxBookingMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnUploadBooking)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContinueBooking)))
                .addGap(476, 476, 476))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 34, 390, 280);

        lnlTitleBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lnlTitleBook.setText("MAKE A BOOKING ");
        getContentPane().add(lnlTitleBook);
        lnlTitleBook.setBounds(6, 6, 185, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setUsername(String username) { // used to get the staff usermname from booking main menu
        this.username = username;
        staffName.setText(username);
    }

    private void membersFill() {//This fills the combo box with member IDs and usernames

        List<Member> allMembers = MemberDAL.getAllMember();

        for (int i = 0; i < allMembers.size(); i++) {
            cbxBookingMember.addItem(allMembers.get(i).getShortString());
        }
    }
//Draft

    /*
    public void AddMembers() {

        ArrayList<Member> c = new ArrayList<Member>();
        c = MemberDAL.getAllMember();
        cbxBookingMember.setModel((ComboBoxModel<String>) c);

        /*
        for (int b = 0; b < c.size(); b++) {
            
break;
        }
     */
    //item1="HI";
    //item2="bye";
    //cbxBookingMemberID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { item1,item2}));
    // }


    private void cbxTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTimeActionPerformed
//boolean isWithinRange(Date chosenDate) {
    // return !(chosenDate.after(currentD));
//}
    private void btnUploadBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadBookingActionPerformed
        /*
        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate currentDate = LocalDate.now();
       // Date currentD=currentDate;
         */
        // System.out.println(currentDate.format(df));
        //this code is used to get the user inputted details and insert them into databse
        //  BookingDate.setMinSelectableDate(new Date()); 

        Date chosenDate = BookingDate.getDate();
        if (chosenDate == null) {
            JOptionPane.showMessageDialog(this, "Need to choose a date");
        } else {
            DateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");//formats the date
            String date = dFormat.format(chosenDate);
            System.out.println(date);

            // System.out.println(date);test
            String chosenTime = cbxTime.getSelectedItem().toString();
            String chosenMember = cbxBookingMember.getSelectedItem().toString();

            String[] split = chosenMember.split(" ");// array is used to split the member ID and username
            String memID = split[0];
            int mID = Integer.parseInt(split[0]);// id
            //System.out.println(memID);
            // int add=1+mID;
            //System.out.println(add);//test if mid is int when trying to convert it from a string
            String memUser = split[1];
            //System.out.println(memUser);

            String chosenStaff = staffName.getText();

            Booking newBooking = new Booking(chosenTime, date, mID, memUser, chosenStaff);
            BookingDAL.insertnewBooking(newBooking);
            JOptionPane.showMessageDialog(this, "Session booked");

        }
    }//GEN-LAST:event_btnUploadBookingActionPerformed

    private void btnContinueBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueBookingActionPerformed
        BookingMenuForm logB = new BookingMenuForm();
        logB.getUsername(username);

        logB.setSize(800, 600);

        logB.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        logB.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnContinueBookingActionPerformed

    private void cbxBookingMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBookingMemberActionPerformed

    }//GEN-LAST:event_cbxBookingMemberActionPerformed

    private void togColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togColourActionPerformed
        Color original = new Color(255, 204, 204);
        if (togColour.isSelected()) {
            //  jPanel1.setBackground(Color.white); cant see buttons
            jPanel1.setBackground(Color.yellow);
            add(jPanel1);
        } else {
            jPanel1.setBackground(original);
            add(jPanel1);
        }


    }//GEN-LAST:event_togColourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingForm().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BookingDate;
    private javax.swing.JButton btnContinueBooking;
    private javax.swing.JButton btnUploadBooking;
    private javax.swing.JComboBox<String> cbxBookingMember;
    private javax.swing.JComboBox<String> cbxTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMemberIDBooking;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lnlTitleBook;
    private javax.swing.JLabel staffName;
    private javax.swing.JToggleButton togColour;
    // End of variables declaration//GEN-END:variables

}
