package gymbookings7095;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Character.isUpperCase;
import java.text.*;
import java.time.*;
import java.util.*;
import org.apache.derby.client.am.DateTime;
import java.awt.Color;

/**
 *
 * @author 7095 This form is used to add new staff members to the database
 */
public class RegisterForm extends javax.swing.JFrame {

    boolean AdminLev = false;//needs to be a global variable as is used in two different methods
    String givenUsername;

    public void setstaffUser(String staffUser) {
        lblUser.setText(staffUser);
        this.givenUsername = staffUser;

    }
    //public String ageCheck(Date chosenDate){
    //}

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();

        // Get today minus 16 years
        LocalDate date = LocalDate.now();
        date = date.minusYears(16L);

        //default time zone
        ZoneId defaultZoneId = ZoneId.systemDefault();

        //creating the instance of LocalDate using the day, month, year info
        LocalDate localDate = LocalDate.of(date.getYear(), date.getMonth(), date.getDayOfMonth());
        System.out.println(localDate);
        //local date + atStartOfDay() + default time zone + toInstant() = Date
        Date sixteenAgo = Date.from(localDate.atStartOfDay(defaultZoneId).toInstant());

        JDOBReg.setMaxSelectableDate(sixteenAgo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegister = new javax.swing.JLabel();
        panMainRegPanel = new javax.swing.JPanel();
        lblUsernameRegister = new javax.swing.JLabel();
        lblPasswordRegister = new javax.swing.JLabel();
        btnContinueReg = new javax.swing.JButton();
        pwdPassReg = new javax.swing.JPasswordField();
        btnUpload = new javax.swing.JButton();
        cbxAdLevel = new javax.swing.JComboBox<>();
        lblDOBReg = new javax.swing.JLabel();
        JDOBReg = new com.toedter.calendar.JDateChooser();
        lblUser = new javax.swing.JLabel();
        togColour = new javax.swing.JToggleButton();

        lblRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRegister.setText("REGISTER NEW STAFF MEMBER");

        panMainRegPanel.setBackground(new java.awt.Color(0, 204, 204));
        panMainRegPanel.setForeground(new java.awt.Color(0, 204, 204));

        lblUsernameRegister.setText("Username ");

        lblPasswordRegister.setText("Password");

        btnContinueReg.setText("Continue");
        btnContinueReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueRegActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload ");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        cbxAdLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff level", "staff", "admin" }));
        cbxAdLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAdLevelActionPerformed(evt);
            }
        });

        lblDOBReg.setText("Date of Birth ");

        JDOBReg.setDateFormatString("yyyy-MM-dd");
        JDOBReg.setMinSelectableDate(new java.util.Date(-946767512000L));

        togColour.setText("Change colour");
        togColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togColourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMainRegPanelLayout = new javax.swing.GroupLayout(panMainRegPanel);
        panMainRegPanel.setLayout(panMainRegPanelLayout);
        panMainRegPanelLayout.setHorizontalGroup(
            panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainRegPanelLayout.createSequentialGroup()
                .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainRegPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsernameRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPasswordRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panMainRegPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDOBReg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainRegPanelLayout.createSequentialGroup()
                        .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdPassReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JDOBReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainRegPanelLayout.createSequentialGroup()
                        .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panMainRegPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(togColour))
                            .addGroup(panMainRegPanelLayout.createSequentialGroup()
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxAdLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpload)
                                    .addComponent(btnContinueReg))))
                        .addGap(18, 18, 18))))
        );
        panMainRegPanelLayout.setVerticalGroup(
            panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainRegPanelLayout.createSequentialGroup()
                .addComponent(togColour)
                .addGap(3, 3, 3)
                .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsernameRegister)
                    .addComponent(cbxAdLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordRegister)
                    .addComponent(pwdPassReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnUpload)
                .addGroup(panMainRegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainRegPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(lblDOBReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panMainRegPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addComponent(JDOBReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContinueReg)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegister)
                    .addComponent(panMainRegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblRegister)
                .addGap(18, 18, 18)
                .addComponent(panMainRegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueRegActionPerformed
        LoginForm log2 = new LoginForm();//this will bring you back to the log in form

        log2.setSize(800, 600);

        log2.setVisible(true);
        this.setVisible(false); //closes the current register form so its a smooth transistion        
//GO TO LOG IN FORM
    }//GEN-LAST:event_btnContinueRegActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        /*
        String Adlevel=""; //this is used to see if the user has chosen staff or admin for their admin level
        if (AdminLev==false){//this is determined through the AdLevelActionPerformed method
         Adlevel="staff";
     }else
     {
         Adlevel="admin";
     }
         */
        if (lblUser.getText().isEmpty()) {//validatoin for empty
            JOptionPane.showMessageDialog(this, "Username or password is empty");
        } else if (pwdPassReg.getPassword().length <= 0) {
            JOptionPane.showMessageDialog(this, "password empty");
        } else {
            String chosenLevel = cbxAdLevel.getSelectedItem().toString();

            char[] givenPassword = pwdPassReg.getPassword(); //as password is in password type it must be converted to a string through a char array through cencantination
            String pass = "";
            for (int i = 0; i < givenPassword.length; i++) {
                pass = pass + givenPassword[i];
                System.out.println(pass.length() + "this is password length");
                System.out.println(pass.charAt(0) + "first charcter");
            }
            if ((pass.length() < 5) || (!Character.isUpperCase(pass.charAt(0)))) {
                JOptionPane.showMessageDialog(this, "Password needs capital at start and needs to be at least 5 characters long" + '\n' + "try again");
            } else {
                String Username = lblUser.getText();//gets username inputted from user

                Date chosenDate = JDOBReg.getDate();//gets inputted date from jdatechooser
                if (chosenDate == null) {
                    JOptionPane.showMessageDialog(this, "Need to choose a date");
                } else {
                    DateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");//format needed in order to be bale to be saved in the database
                    String date = dFormat.format(chosenDate);
                    // System.out.println(date); test if the date is stored in variable date
                    System.out.println(chosenLevel);
                    if (chosenLevel.equals("admin") || chosenLevel.equals("staff")) {
                        Staff newStaff = new Staff(Username, pass, chosenLevel, date);
                        StaffDAL.insertnewStaff(newStaff); //ueses method from dal to insert new staff object into the staff table
                        //pop up 
                        JOptionPane.showMessageDialog(this, "Staff member added");
                    } else {
                        JOptionPane.showMessageDialog(this, "need to choose an admin level");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed


    private void cbxAdLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAdLevelActionPerformed
        /*        
//used to see if staff or admin has been chosen for admin level
        String Adlevel = "";

        if (Adlevel.equals("Staff")) {
            AdminLev = false;
        } else if (Adlevel.equals("Admin")) {
            AdminLev = true;
        } /*else if (Adlevel.equals("Staff level")){
            System.out.println("choose an admin level");
        }
         */

    }//GEN-LAST:event_cbxAdLevelActionPerformed

    private void togColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togColourActionPerformed
        Color original = new Color(0, 204, 204);
        if (togColour.isSelected()) {
            //  jPanel1.setBackground(Color.white); cant see buttons
            panMainRegPanel.setBackground(Color.yellow);
            add(panMainRegPanel);
        } else {
            panMainRegPanel.setBackground(original);
            add(panMainRegPanel);
        }
    }//GEN-LAST:event_togColourActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDOBReg;
    private javax.swing.JButton btnContinueReg;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cbxAdLevel;
    private javax.swing.JLabel lblDOBReg;
    private javax.swing.JLabel lblPasswordRegister;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsernameRegister;
    private javax.swing.JPanel panMainRegPanel;
    private javax.swing.JPasswordField pwdPassReg;
    private javax.swing.JToggleButton togColour;
    // End of variables declaration//GEN-END:variables

}
