/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymbookings7095;
//valided by if statement so iuf continue pressed but no username will stop you

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aaronmontgomery
 */
public class UsernameForm extends javax.swing.JFrame {

    String staffUser;
    boolean username = false;

   

    /**
     * Creates new form UsernameForm
     */
    public UsernameForm() {
        initComponents();
    }
 public boolean intInString(String fore,String sur){
     System.out.println("in method");
     boolean check=true;//initailses variables
     boolean check1=true;
     boolean check2=true;
     char[] ch = fore.toCharArray(); //converts Strings to characheter array
     for( int i=0;i<ch.length;i++){
          check1=Character.isLetter(ch[i]); //checks if there is a number in array
          if(check1==false){ 
              check=false;
          }
          
          System.out.println(ch[i]+"this is i");
          System.out.println("in first for");
          System.out.println("check1 resultttt"+check1);
 }
     char[] c=sur.toCharArray();
     for( int j=0;j<c.length;j++){
          check2=Character.isLetter(c[j]);
           if(check2==false){
              check=false;
          }
     }
     /*
     if(check1==false){
         check=false;
     }else if(check2==false){
         check=false;
     }
     */
     System.out.println("check result"+check);
        return check;
     }
   
     
 
 
    /*
    public boolean intInString(String fore,String sur){
        System.out.println("test "+ fore+sur);
      boolean integer =false;
        try {
   int Forename = Integer.parseInt(fore);
    int surename = Integer.parseInt(sur);
  integer=true;
    if(integer){
        JOptionPane.showMessageDialog(this, "Can not accept integers in username");
    }
} catch (NumberFormatException e) {
    
    System.out.println("Input String cannot be parsed to Integer.");
integer=false;
            System.out.println("no numbers dub");
}
    return integer;
   
    }
     */
/*
    public static boolean isInteger(String fore, String sur) {
        boolean intinThere = false;
        for (char c : fore.toCharArray()) {
            System.out.println("infor for");
            if (!Character.isDigit(c)) {
                intinThere = true;
                
            }

        }
        for (char c : sur.toCharArray()) {
            System.out.println("in sur for");
            if (!Character.isDigit(c)) {
                intinThere = true;
                
            }
        }
        return intinThere;
    }
    */
   
    

    /*
    public static boolean isInteger(String fore,String sur) {
    int intValue;
        System.out.println("reached method");
		
    System.out.println(String.format("Parsing string: \"%s\"", fore,sur));
		
    if(fore == null || fore.equals("")) {
        System.out.println("forename cannot be parsed, it is null or empty.");
        return false;
    }
    		
    if(sur == null || sur.equals("")) {
        System.out.println("surename cannot be parsed, it is null or empty.");
        return false;
    }
    
    try {
        intValue = Integer.parseInt(fore);
        intValue = Integer.parseInt(sur);
        return true;
    } catch (NumberFormatException e) {
        System.out.println("Input String cannot be parsed to Integer.");
    }
    return false;
}
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtForename = new javax.swing.JTextField();
        lblForename = new javax.swing.JLabel();
        lblSurename = new javax.swing.JLabel();
        txtSurename = new javax.swing.JTextField();
        btnCreateU = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        togColour = new javax.swing.JToggleButton();
        lblCreateUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        lblForename.setText("Enter Forename");

        lblSurename.setText("Enter Surename");

        txtSurename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurenameActionPerformed(evt);
            }
        });

        btnCreateU.setText("Create Username");
        btnCreateU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUActionPerformed(evt);
            }
        });

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        togColour.setText("Change colour");
        togColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togColourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForename, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSurename, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtForename, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtSurename))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addComponent(togColour, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(togColour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblForename))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurename)
                    .addComponent(txtSurename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnCreateU)
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblCreateUser.setText("Create Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCreateUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateUser)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSurenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurenameActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        if (username == true) {
            RegisterForm logf = new RegisterForm();// Opens login form
            logf.setstaffUser(staffUser);
            logf.setSize(800, 600);

            logf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            logf.setVisible(true);
            this.setVisible(false); //use in testtttttttttttt5tttttttttttttt
        } else {
            JOptionPane.showMessageDialog(this, "Need to create a username");
        }
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnCreateUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUActionPerformed
        String givenFor = txtForename.getText();

        String givensur = txtSurename.getText();
       boolean intCheck=intInString(givenFor,givensur);
       if(intCheck==false){
           JOptionPane.showMessageDialog(this, "Username can not have numeber in it");
       }else{
        
            if (txtForename.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Need to enter a forename or surename ");
            } else if (txtSurename.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Need to enter a surename ");
            } else {
                //test
                givenFor = givenFor.substring(0, 1).toUpperCase() + givenFor.substring(1);
                givensur = givensur.substring(0, 1).toUpperCase() + givensur.substring(1);
                System.out.println(givenFor + givensur + "test");
                this.staffUser = givenFor.charAt(0) + givensur;
                username = true;
                JOptionPane.showMessageDialog(this, "your username is " + staffUser);
            }
       }
            /*
        intInString(givenFor,givensur);
        if(true){
            System.out.println("there is an int");
            
        }else{
         */
 /*
if(isInteger(givenFor,givensur)) { 
    System.out.println("String is numeric!");
    boolean integer=true;
    
} else {
    System.out.println("String is not numeric.");
    integer=false;
}
         */
/*
        isInteger(givenFor, givensur);
        if (integer == true) {
            JOptionPane.showMessageDialog(this, "Can not accept integers in username");
        } else {
*/
        
    }//GEN-LAST:event_btnCreateUActionPerformed

    private void togColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togColourActionPerformed
        Color original = new Color(102,153,255);
        if(togColour.isSelected()){
            //  jPanel1.setBackground(Color.white); cant see buttons
            jPanel1.setBackground(Color.yellow);
            add(jPanel1);
        }else{
            jPanel1.setBackground(original);
            add(jPanel1);
        }
    }//GEN-LAST:event_togColourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsernameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsernameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnCreateU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreateUser;
    private javax.swing.JLabel lblForename;
    private javax.swing.JLabel lblSurename;
    private javax.swing.JToggleButton togColour;
    private javax.swing.JTextField txtForename;
    private javax.swing.JTextField txtSurename;
    // End of variables declaration//GEN-END:variables
}
